-- các kiểu dũ liệu database hay dùng

-- int: kiểu số nguyên, VD: 1,5,6,-4,-9
-- float: kiểu số thưc, VD: 1.4, 5,-5, 4.6
-- char: kiểu kí tự, ko viết được tiêng việt, bộ nhớ cấp phát cứng Vd: a,A,N,n,f (char(10) bắt buộc phải để trống 10 ô ra)
-- bộ nhớ khi viết tiếng việt thì chỉ bằng 1 nửa khi ko viết tiếng việt 
-- varchar: kiểu kí tự, ko viết được tiêng việt, bộ nhớ cấp phát động, VD varchar(10) nếu ta nhập "conga" thì chỉ phải để tróng ra 5 ô thôi.
-- nchar: kiểu kí tự, giống hệ char chỉ khác là viết được tiến viết.
-- nvarchar: kiểu kí tự, giống hệt varchar chỉ khác là viêt đươc tiếng việt.
-- date: ngày, tháng, năm, giờ.
-- time: chỉ giờ, phút, giây,
-- bit: kiêu dữ liệu chỉ 0 và 1
-- text: lưu văn bản lơn
-- ntext: lưu văn bản lớn có viết tiếng việt.